# Generated by Django 4.1.7 on 2023-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_member_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='img',
        ),
        migrations.AlterField(
            model_name='member',
            name='des',
            field=models.CharField(max_length=511, verbose_name='Описание'),
        ),
    ]
