# Generated by Django 4.1.7 on 2023-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/comment.jpg', null=True, upload_to='products/', verbose_name='Фотография 1:1'),
        ),
    ]
