# Generated by Django 4.1.7 on 2023-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='placeholders/partners.jpg', upload_to='partners/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
