# Generated by Django 4.1.7 on 2023-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_partners_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='des',
            field=models.CharField(max_length=511, verbose_name='Описание 511зн.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='job',
            field=models.CharField(max_length=255, verbose_name='Должность 255зн.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя и Фамилия 255зн.'),
        ),
    ]
