# Generated by Django 4.2.1 on 2023-05-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_member_des_alter_member_job_alter_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='des',
        ),
    ]
