# Generated by Django 4.2.1 on 2023-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_member_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_img', models.ImageField(blank=True, default='placeholders/slide.jpg', null=True, upload_to='slide/', verbose_name='Изображение для десктопа')),
                ('mobile_img', models.ImageField(blank=True, default='placeholders/slide.jpg', null=True, upload_to='slide/', verbose_name='Изображение для моб.устройств')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
