# Generated by Django 4.2.1 on 2023-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_slide_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='button1',
            field=models.BooleanField(default=0, verbose_name='Нужна ли кнопка 1 (Если галочка не стоит - кнопка отображаться не будет)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='button1_text',
            field=models.CharField(default=0, max_length=24, verbose_name='Текст для кнопки 1 (24 зн.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='button1_url',
            field=models.CharField(default=0, max_length=1024, verbose_name='Ссылка для кнопки 1 (1024 зн.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='button2',
            field=models.BooleanField(default=0, verbose_name='Нужна ли кнопка 2 (Если галочка не стоит - кнопка отображаться не будет)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='button2_text',
            field=models.CharField(default=0, max_length=24, verbose_name='Текст для кнопки 2 (24 зн.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='button2_url',
            field=models.CharField(default=0, max_length=1024, verbose_name='Ссылка для кнопки 2 (1024 зн.)'),
            preserve_default=False,
        ),
    ]
