# Generated by Django 4.2.1 on 2023-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_slide_button1_slide_button1_text_slide_button1_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='placeholders/aboutusslide.jpg', upload_to='partners/', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'слайд (о нас)',
                'verbose_name_plural': 'Слайды',
                'ordering': ['id'],
            },
        ),
    ]
