# Generated by Django 4.2.1 on 2023-06-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_aboutusslide_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/partners.jpg', upload_to='partners/', verbose_name='Изображение партнера 211х45 .png'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='desktop_img',
            field=models.ImageField(blank=True, default='placeholders/slide.jpg', null=True, upload_to='slide/', verbose_name='Изображение для десктопа 2354х1002 .png'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='mobile_img',
            field=models.ImageField(blank=True, default='placeholders/slide.jpg', null=True, upload_to='slide/', verbose_name='Изображение для моб.устройств 766х892 .png'),
        ),
    ]
