# Generated by Django 4.2.1 on 2023-06-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_partners_img_alter_slide_desktop_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=24, verbose_name='Время начала. Например 10:00 (24 зн.)')),
                ('finish_time', models.CharField(max_length=24, verbose_name='Время конца. Например 22:00 (24 зн.)')),
                ('utc_text', models.CharField(max_length=56, verbose_name="Часовой пояс. Например 'По московскому времени' (56 зн.)")),
                ('city', models.CharField(max_length=56, verbose_name="Город. Например 'г. Москва' (56 зн.)")),
                ('address', models.CharField(max_length=128, verbose_name="Адрес. Например 'ул. Краснобогатырская 2, стр. 4' (128 зн.)")),
                ('contacts', models.CharField(max_length=56, verbose_name="Контакты. Например '+7 9999 - 623 - 469' (56 зн.)")),
            ],
            options={
                'verbose_name': 'цех',
                'verbose_name_plural': 'Цеха',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='partners',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/partners.jpg', upload_to='partners/', verbose_name='Изображение партнера'),
        ),
    ]
