# Generated by Django 4.2.1 on 2023-06-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_manufactory_alter_partners_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactory',
            options={'ordering': ['id'], 'verbose_name': 'цех', 'verbose_name_plural': 'Цеха'},
        ),
    ]
