# Generated by Django 4.2.1 on 2023-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_manufactory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=56, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=128, verbose_name='Почта')),
                ('telegram', models.CharField(max_length=128, verbose_name='Телеграм')),
                ('whatsapp', models.CharField(max_length=128, verbose_name='Ватсап')),
                ('vk', models.CharField(max_length=128, verbose_name='Вк')),
                ('inn', models.CharField(max_length=128, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=128, verbose_name='ОГРН')),
            ],
            options={
                'verbose_name': 'конфигурацию',
                'verbose_name_plural': 'Конфигурация сайта',
                'ordering': ['id'],
            },
        ),
    ]
