# Generated by Django 4.2.1 on 2023-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='yandex',
            field=models.CharField(default=0, max_length=512, verbose_name='Ссылка на местоположение (Яндекс.Карты)'),
            preserve_default=False,
        ),
    ]
