# Generated by Django 4.2.1 on 2023-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_siteconfiguration_yandex'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_us_text',
            field=models.TextField(default='', verbose_name="Текст на странице 'О нас'"),
            preserve_default=False,
        ),
    ]
