# Generated by Django 4.2.1 on 2023-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_siteconfiguration_about_us_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone_link',
            field=models.CharField(default=0, max_length=56, verbose_name='Номер телефона (Содержащий только цифры и знак плюса, без пробелов, без дефисов)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(max_length=56, verbose_name='Номер телефона (Удобный для чтения)'),
        ),
    ]
