# Generated by Django 4.1.7 on 2023-03-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_member_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name'], 'verbose_name': 'члена команды', 'verbose_name_plural': 'Члены команды'},
        ),
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/placeholder.jpg', null=True, upload_to='members/', verbose_name='Фотография (исключительно квадратные)'),
        ),
    ]
