# Generated by Django 4.1.7 on 2023-03-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/categories.jpg', null=True, upload_to='categories/', verbose_name='Фотография 1:1 с прозрачным фоном'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/product.jpg', null=True, upload_to='products/', verbose_name='Фотография 1:1 с прозрачным фоном'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=0, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/product.jpg', null=True, upload_to='products/', verbose_name='Фотография 1:1'),
        ),
    ]
