# Generated by Django 4.1.7 on 2023-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_comment_options_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование 128зн.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='des',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование 128зн.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Ссылка на видео в youtube 1024зн.'),
        ),
    ]
