# Generated by Django 4.2.1 on 2023-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_category_name_alter_product_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка (0-100)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование 512зн.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/product.jpg', null=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование 512зн.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ссылка на видео в youtube 1024зн.'),
        ),
    ]
