# Generated by Django 4.2.1 on 2023-05-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_discount_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
