# Generated by Django 4.2.1 on 2023-05-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_comment_review_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование 512зн.')),
                ('value', models.CharField(max_length=512, verbose_name='Значение 512зн.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
                'ordering': ['product'],
            },
        ),
    ]
