# Generated by Django 4.2.1 on 2023-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=5, verbose_name='Оценка'),
        ),
    ]
