# Generated by Django 4.2.1 on 2023-05-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/categories.jpg', null=True, upload_to='categories/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/product.jpg', null=True, upload_to='products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/comment.png', null=True, upload_to='users/', verbose_name='Фотография'),
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='placeholders/review.jpg', null=True, upload_to='products/', verbose_name='Фотография')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'изображение к отзыву',
                'verbose_name_plural': 'Изображения к отзыву',
                'ordering': ['review'],
            },
        ),
    ]
