# Generated by Django 4.2.1 on 2023-05-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_category_img_alter_productimages_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='completed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
