# Generated by Django 4.2.1 on 2023-05-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_reviewimages_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimages',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.review', verbose_name='Отзыв'),
        ),
    ]
