# Generated by Django 4.2.1 on 2023-05-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_reviewimages_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
