# Generated by Django 4.2.1 on 2023-06-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_options_product_prio_alter_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=1, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_count',
            field=models.IntegerField(default=0, verbose_name='С какого кол-ва товаров будет считать Цена мелкий опт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/categories.jpg', null=True, upload_to='categories/', verbose_name='Изображение 260х300'),
        ),
    ]
