# Generated by Django 4.2.1 on 2023-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_productoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2),
        ),
    ]
