# Generated by Django 4.2.1 on 2023-06-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_productoption_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование (512 зн.)')),
            ],
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='option',
        ),
        migrations.AddField(
            model_name='productoption',
            name='option_value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.productoptionvalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='value',
            field=models.CharField(max_length=512, verbose_name='Значение (512 зн.)'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='option_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.productoptionname'),
            preserve_default=False,
        ),
    ]
