# Generated by Django 4.2.1 on 2023-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_productoption_option_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['id'], 'verbose_name': 'Варианты товара', 'verbose_name_plural': 'Варианты товара'},
        ),
        migrations.AddField(
            model_name='productoption',
            name='values',
            field=models.TextField(default=0, verbose_name="Варианты (Перечислите их, разделяя символом ';'"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoption',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.DeleteModel(
            name='ProductOptionValue',
        ),
    ]
