# Generated by Django 4.2.1 on 2023-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_productoption_options_productoption_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prio',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
    ]
