# Generated by Django 4.2.1 on 2023-06-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_category_prio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-prio'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
