# Generated by Django 4.2.1 on 2023-06-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_unit',
            field=models.IntegerField(default=1, verbose_name='Минимальное кол-во доступное для покупки'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт.', max_length=16, verbose_name="Единица измерения. Например 'шт.' или  'пара(ы)'"),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(verbose_name='Скидка (Положительное число от 0 до 100)'),
        ),
    ]
