# Generated by Django 4.2.1 on 2023-06-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_product_min_unit_product_unit_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='values',
        ),
        migrations.AddField(
            model_name='productoption',
            name='retail_price',
            field=models.IntegerField(default=0, verbose_name='Розничная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoption',
            name='wholesale_price',
            field=models.IntegerField(default=0, verbose_name='Оптовая цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт.', max_length=16, verbose_name="Единица измерения. Например 'шт.' или  'пара'"),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ссылка на видео в youtube 1024зн. (пока что не используется)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_count',
            field=models.IntegerField(verbose_name='С какого кол-ва товаров будет считаться оптовая цена'),
        ),
    ]
