# Generated by Django 4.2.1 on 2023-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_productoption_uni_id_productoption_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='value',
            field=models.CharField(max_length=512, verbose_name='Текст на кнопке'),
        ),
    ]
