# Generated by Django 4.2.1 on 2023-06-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_productoption_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-prio', 'id'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='uni_id',
        ),
    ]
