# Generated by Django 4.2.1 on 2023-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_product_options_remove_productoption_uni_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='retail_price_h',
            field=models.IntegerField(default=0, verbose_name='Розничная цена(Указать цену не учитывая скидку)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoption',
            name='retail_price',
            field=models.IntegerField(verbose_name='Розничная цена(Не заполнять)'),
        ),
    ]
