# Generated by Django 4.2.1 on 2023-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_productoption_retail_price_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='retail_price',
            field=models.IntegerField(verbose_name='Розничная цена'),
        ),
    ]
