# Generated by Django 4.2.1 on 2023-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_product_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(default='', max_length=512, verbose_name='Артикул'),
        ),
    ]
