# Generated by Django 4.2.1 on 2023-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_product_articul'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristic',
            name='its_articul',
            field=models.BooleanField(default=0, verbose_name='Это артикул'),
        ),
    ]
