# Generated by Django 4.2.1 on 2023-06-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_productcharacteristic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'ordering': ['-its_articul', 'product'], 'verbose_name': 'характеристика товара', 'verbose_name_plural': 'Характеристики товара'},
        ),
    ]
