# Generated by Django 4.2.1 on 2023-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_productinbasket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=0, verbose_name='Старая цена (Будет автоматически рассчитана)'),
        ),
    ]
