# Generated by Django 4.2.1 on 2023-07-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='des',
            field=models.CharField(default=' ', max_length=512, verbose_name='Описание 512зн.'),
            preserve_default=False,
        ),
    ]
