# Generated by Django 4.2.1 on 2023-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_category_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Неактивный'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='unique_id',
            field=models.CharField(max_length=32, verbose_name='Уникальный идентификатор'),
        ),
    ]
