# Generated by Django 4.2.1 on 2023-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_category_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='unique_id',
            field=models.CharField(max_length=32, verbose_name='Уникальный идентификатор'),
        ),
    ]
