# Generated by Django 4.2.1 on 2023-12-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_product_inactive_alter_basket_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='options',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productoption', verbose_name='Опции'),
        ),
    ]
