# Generated by Django 4.2.13 on 2024-05-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_productinbasket_options'),
        ('shop', '0058_product_inactive_alter_productinbasket_options'),
    ]

    operations = [
    ]
