# Generated by Django 4.2.8 on 2024-11-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_productinbasket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Нужно для CEO (Заполняется автоматически)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Нужно для CEO (Заполняется автоматически)'),
        ),
    ]
