# Generated by Django 4.2.8 on 2024-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование 512зн.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True, verbose_name='Нужно для CEO (Заполняется автоматически, если поле пустое)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование 512зн.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True, verbose_name='Нужно для CEO (Заполняется автоматически, если поле пустое)'),
        ),
    ]
