# Generated by Django 4.2.13 on 2024-11-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_merge_20240523_2156'),
        ('shop', '0063_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
    ]
