# Generated by Django 4.2.13 on 2024-11-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_alter_category_name_alter_product_name'),
        ('shop', '0064_merge_20241116_1306'),
    ]

    operations = [
    ]
