# Generated by Django 4.2.8 on 2025-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_merge_20241116_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_name_suffix',
            field=models.CharField(default='', max_length=64),
        ),
    ]
