# Generated by Django 4.2.1 on 2023-06-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_basket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasketoption',
            name='product_in_basket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.productinbasket'),
            preserve_default=False,
        ),
    ]
