# Generated by Django 4.2.1 on 2023-06-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_category_options'),
        ('CRM', '0009_productinbasketoption_product_in_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInSendedBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('options', models.TextField(default='', verbose_name='Опции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.order', verbose_name='Владелец заявки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['product'],
            },
        ),
    ]
