# Generated by Django 4.2.1 on 2023-06-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_product_options_remove_productoption_uni_id'),
        ('CRM', '0012_alter_productinsendedbasket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('options', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productoption', verbose_name='Опции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.order', verbose_name='Владелец заявки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['product'],
            },
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='options',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productoption', verbose_name='Опции'),
        ),
        migrations.DeleteModel(
            name='ProductInSendedBasket',
        ),
    ]
