# Generated by Django 4.2.1 on 2023-06-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_productoption_retail_price_h_and_more'),
        ('CRM', '0013_productinorder_productinbasket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='options',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='shop.productoption', verbose_name='Опции'),
        ),
    ]
