# Generated by Django 4.2.1 on 2023-06-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_alter_productinorder_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInBasketOption',
        ),
    ]
