# Generated by Django 4.2.1 on 2023-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_alter_productinorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='summ',
            field=models.CharField(default='0', max_length=512, verbose_name='Общая сумма'),
        ),
    ]
