# Generated by Django 4.2.1 on 2023-06-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='options',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='product',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
    ]
