# Generated by Django 4.2.1 on 2023-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0021_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=50, null=True, verbose_name='ФИО клиента'),
        ),
    ]
