# Generated by Django 4.2.1 on 2023-07-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_question_created_at_alter_question_contacts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ на консультацию', 'verbose_name_plural': 'Заказ на консультацию'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'обращение или вопрос', 'verbose_name_plural': 'Обращения и вопросы'},
        ),
    ]
