# Generated by Django 4.2.1 on 2023-07-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0024_alter_consultation_options_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заявку', 'verbose_name_plural': 'Заявки'},
        ),
    ]
