# Generated by Django 4.2.1 on 2023-07-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0025_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Текст обращения'),
        ),
    ]
