# Generated by Django 4.2.8 on 2024-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0026_alter_order_client_name_alter_question_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='its_spam',
            field=models.BooleanField(default=False, verbose_name='Спам'),
        ),
    ]
