# Generated by Django 4.1.7 on 2023-03-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.CharField(default='', max_length=1024, verbose_name='Ссылка на видео в youtube'),
        ),
    ]
