# Generated by Django 4.1.7 on 2023-03-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_member_img_alter_member_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/placeholder.jpg', null=True, upload_to='members/'),
        ),
    ]
