# Generated by Django 4.1.7 on 2023-03-20 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_comment_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0002_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('contacts', models.CharField(max_length=50, verbose_name='Контакты клиента')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'Заявки',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Product_in_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.order', verbose_name='Товары в корзинах')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'товар в корзине',
                'verbose_name_plural': 'Товары в корзинах',
                'ordering': ['product'],
            },
        ),
    ]
