# Generated by Django 4.1.7 on 2023-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_order_product_in_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summ',
            field=models.IntegerField(default=0, verbose_name='Сумма заявки'),
            preserve_default=False,
        ),
    ]
