# Generated by Django 4.1.7 on 2023-03-20 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_comment_created_at'),
        ('CRM', '0004_order_summ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_in_basket',
            options={'ordering': ['product'], 'verbose_name': 'товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_in_basket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.order', verbose_name='Владелец заявки'),
        ),
        migrations.AlterField(
            model_name='product_in_basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар'),
        ),
    ]
