# Generated by Django 4.1.7 on 2023-03-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('contacts', models.CharField(max_length=124, verbose_name='Контакты клиента')),
                ('text', models.CharField(max_length=2024, verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'обращение и вопрос',
                'verbose_name_plural': 'Обращения и вопросы',
                'ordering': ['name'],
            },
        ),
    ]
