# Generated by Django 4.1.7 on 2023-03-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_count',
            field=models.IntegerField(default=0, verbose_name='Сколько раз приобретали'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/product.jpg', null=True, upload_to='products/', verbose_name='Фотография 500x500'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='placeholders/product.jpg', null=True, upload_to='products/', verbose_name='Фотография главная 500x500'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='placeholders/product.jpg', null=True, upload_to='products/', verbose_name='Фотография 500x500')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'Изображения товара',
                'ordering': ['product'],
            },
        ),
    ]
